const express = require("express");
const adminAuthRoutes = require("./adminRoutes/adminAuthRoutes");
const adminDashboardRoutes = require("./adminRoutes/adminDashboardRoutes");
const adminAppConfigRoutes = require("./adminRoutes/adminAppConfigRoutes");
const adminFaqRoutes = require("./adminRoutes/adminFaqRoutes");
const adminCouponRoutes = require("./adminRoutes/adminCouponRoutes");
const adminNotificationRoutes = require("./adminRoutes/adminNotificationRoutes");
const adminStaticPageRoutes = require("./adminRoutes/adminStaticPageRoutes");
const adminTransformationRoutes = require("./adminRoutes/adminTransformationRoutes");
const adminBannerRoutes = require("./adminRoutes/adminBannerRoutes");
const adminHealthConcernRoutes = require("./adminRoutes/adminHealthConcernRoutes");
const adminHealthDisorderRoutes = require("./adminRoutes/adminHealthDisorderRoutes");
const adminHealthToolRoutes = require("./adminRoutes/adminHealthToolRoutes");
const adminHealthRecipeRoutes = require("./adminRoutes/adminHealthRecipeRoutes");
const adminYogaRoutes = require("./adminRoutes/adminYogaRoutes");
const adminPhysicalExerciseRoutes = require("./adminRoutes/adminPhysicalExerciseRoutes");
const adminSupplementRoutes = require("./adminRoutes/adminSupplementRoutes");
const adminMedicalConditionQuestionRoutes = require("./adminRoutes/adminMedicalConditionQuestionRoutes");
const adminLaunchQuestionRoutes = require("./adminRoutes/adminLaunchQuestionRoutes");
const adminLaunchFocusAreaRoutes = require("./adminRoutes/adminLaunchFocusAreaRoutes");
const adminPrakrutiQuestionRoutes = require("./adminRoutes/adminPrakrutiQuestionRoutes");
const adminPrakrutiThingToAvoidRoutes = require("./adminRoutes/adminPrakrutiThingToAvoidRoutes");
const adminPrakrutiRecommendationRoutes = require("./adminRoutes/adminPrakrutiRecommendationRoutes");
const adminTestCatalogRoutes = require("./adminRoutes/adminTestCatalogRoutes");
const adminDietPlanCatalogRoutes = require("./adminRoutes/adminDietPlanCatalogRoutes");
const adminWellnessPrescriptionCatalogRoutes = require("./adminRoutes/adminWellnessPrescriptionCatalogRoutes");
const adminMentalWellbeingRoutes = require("./adminRoutes/adminMentalWellbeingRoutes");
const adminUserRoutes = require("./adminRoutes/adminUserRoutes");
const adminReminderRoutes = require("./adminRoutes/adminReminderRoutes");
const adminHealDietPlanRoutes = require("./adminRoutes/adminHealDietPlanRoutes");
const adminHealWellnessPrescriptionRoutes = require("./adminRoutes/adminHealWellnessPrescriptionRoutes");
const adminHealTestRecommendationRoutes = require("./adminRoutes/adminHealTestRecommendationRoutes");
const adminHealPhysicalExerciseRoutes = require("./adminRoutes/adminHealPhysicalExerciseRoutes");
const adminHealMentalWellbeingRoutes = require("./adminRoutes/adminHealMentalWellbeingRoutes");
const adminHealSupplementRecommendationRoutes = require("./adminRoutes/adminHealSupplementRecommendationRoutes");
const adminHealSupplementDosageRoutes = require("./adminRoutes/adminHealSupplementDosageRoutes");
const adminHealMealTrackingRoutes = require("./adminRoutes/adminHealMealTrackingRoutes");
const adminHealHealthProgressRoutes = require("./adminRoutes/adminHealHealthProgressRoutes");
const adminHealMetabolicMetricsRoutes = require("./adminRoutes/adminHealMetabolicMetricsRoutes");
const adminHealDailyReflectionRoutes = require("./adminRoutes/adminHealDailyReflectionRoutes");
const adminHealConsultancyTrackRoutes = require("./adminRoutes/adminHealConsultancyTrackRoutes");
const adminHealCoachInsightRoutes = require("./adminRoutes/adminHealCoachInsightRoutes");
const adminHealUserCommitmentLetterRoutes = require("./adminRoutes/adminHealUserCommitmentLetterRoutes");
const adminHealLaunchAssessmentRoutes = require("./adminRoutes/adminHealLaunchAssessmentRoutes");
const adminHealPrakrutiAssessmentRoutes = require("./adminRoutes/adminHealPrakrutiAssessmentRoutes");
const adminWellnessCoachRoutes = require("./adminRoutes/adminWellnessCoachRoutes");
const adminSpecializationRoutes = require("./adminRoutes/adminSpecializationRoutes");
const adminBirthdayNotificationRoutes = require("./adminRoutes/adminBirthdayNotificationRoutes");
const adminBirthdayPostRoutes = require("./adminRoutes/adminBirthdayPostRoutes");
const adminClientTestimonialsRoutes = require("./adminRoutes/adminClientTestimonialsRoutes");
const adminLeadershipNoteRoutes = require("./adminRoutes/adminLeadershipNoteRoutes");
const adminProgramTestimonialRoutes = require("./adminRoutes/adminProgramTestimonialRoutes");
const adminVideoTestimonialsRoutes = require("./adminRoutes/adminVideoTestimonialsRoutes");
const adminRealPeopleTestimonialRoutes = require("./adminRoutes/adminRealPeopleTestimonialRoutes");
const adminCommitmentLetterRoutes = require("./adminRoutes/adminCommitmentLetterRoutes");
const adminMonthlyChampionRoutes = require("./adminRoutes/adminMonthlyChampionRoutes");
const adminCofounderMessageRoutes = require("./adminRoutes/adminCofounderMessageRoutes");
const adminContactInquiryRoutes = require("./adminRoutes/adminContactInquiryRoutes");
const adminConsultancyRoutes = require("./adminRoutes/adminConsultancyRoutes");
const adminEnergyExchangeRoutes = require("./adminRoutes/adminEnergyExchangeRoutes");
const adminProgramCatalogRoutes = require("./adminRoutes/adminProgramCatalogRoutes");
const adminMealTrackingRoutes = require("./adminRoutes/adminMealTrackingRoutes");
const adminRoleRoutes = require("./adminRoutes/adminRoleRoutes");
const adminPermissionRoutes = require("./adminRoutes/adminPermissionRoutes");
const publicAppConfigRoutes = require("./publicRoutes/publicAppConfigRoutes");
const miscRoutes = require("./userRoutes/miscRoutes");
const userAuthRoutes = require("./userRoutes/authRoutes");
const waterTrackingRoutes = require("./userRoutes/waterTrackingRoutes");
const stepsTrackingRoutes = require("./userRoutes/stepsTrackingRoutes");
const sleepTrackingRoutes = require("./userRoutes/sleepTrackingRoutes");
const heartRateTrackingRoutes = require("./userRoutes/heartRateTrackingRoutes");
const birthdayPostRoutes = require("./userRoutes/birthdayPostRoutes");
const userNotificationRoutes = require("./userRoutes/notificationRoutes");
const consultancyPaymentRoutes = require("./userRoutes/consultancyPaymentRoutes");
const subscriptionPaymentRoutes = require("./userRoutes/subscriptionPaymentRoutes");
const energyExchangeRoutes = require("./userRoutes/energyExchangeRoutes");
const programRoutes = require("./userRoutes/programRoutes");
const paidOnboardingRoutes = require("./userRoutes/paidOnboardingRoutes");
const userReminderRoutes = require("./userRoutes/reminderRoutes");
const userMealTrackingRoutes = require("./userRoutes/mealTrackingRoutes");
const userRealPeopleTestimonialRoutes = require("./userRoutes/realPeopleTestimonialRoutes");
const userClientTestimonialRoutes = require("./userRoutes/clientTestimonialRoutes");
const commitmentLetterRoutes = require("./userRoutes/commitmentLetterRoutes");
const monthlyChampionRoutes = require("./userRoutes/monthlyChampionRoutes");
const internalParameterRoutes = require("./userRoutes/internalParameterRoutes");
const dietPlanCatalogRoutes = require("./userRoutes/dietPlanCatalogRoutes");
const physicalExerciseRoutes = require("./userRoutes/physicalExerciseRoutes");
const mentalWellbeingRoutes = require("./userRoutes/mentalWellbeingRoutes");
const launchAssessmentRoutes = require("./userRoutes/launchAssessmentRoutes");
const prakrutiAssessmentRoutes = require("./userRoutes/prakrutiAssessmentRoutes");
const healthProgressRoutes = require("./userRoutes/healthProgressRoutes");
const metabolicMetricsRoutes = require("./userRoutes/metabolicMetricsRoutes");
const healConsultancyTrackRoutes = require("./userRoutes/healConsultancyTrackRoutes");
const dailyReflectionRoutes = require("./userRoutes/dailyReflectionRoutes");
const coachInsightRoutes = require("./userRoutes/coachInsightRoutes");
const supplementRecommendationRoutes = require("./userRoutes/supplementRecommendationRoutes");
const supplementDosageRoutes = require("./userRoutes/supplementDosageRoutes");
const wellnessPrescriptionRoutes = require("./userRoutes/wellnessPrescriptionRoutes");
const coachAuthRoutes = require("./wellnessCoachRoutes/coachAuthRoutes");
const coachDashboardRoutes = require("./wellnessCoachRoutes/coachDashboardRoutes");
const coachSpecializationRoutes = require("./wellnessCoachRoutes/coachSpecializationRoutes");
const coachHealUserRoutes = require("./wellnessCoachRoutes/coachHealUserRoutes");
const coachReminderRoutes = require("./wellnessCoachRoutes/coachReminderRoutes");
const coachTestRecommendationRoutes = require("./wellnessCoachRoutes/coachTestRecommendationRoutes");
const coachWellnessPrescriptionRoutes = require("./wellnessCoachRoutes/coachWellnessPrescriptionRoutes");
const coachDietPlanCatalogRoutes = require("./wellnessCoachRoutes/coachDietPlanCatalogRoutes");
const coachPhysicalExerciseRoutes = require("./wellnessCoachRoutes/coachPhysicalExerciseRoutes");
const coachMentalWellbeingRoutes = require("./wellnessCoachRoutes/coachMentalWellbeingRoutes");
const coachSupplementRecommendationRoutes = require("./wellnessCoachRoutes/coachSupplementRecommendationRoutes");
const coachSupplementDosageRoutes = require("./wellnessCoachRoutes/coachSupplementDosageRoutes");
const coachMealTrackingRoutes = require("./wellnessCoachRoutes/coachMealTrackingRoutes");
const coachLaunchAssessmentRoutes = require("./wellnessCoachRoutes/coachLaunchAssessmentRoutes");
const coachPrakrutiAssessmentRoutes = require("./wellnessCoachRoutes/coachPrakrutiAssessmentRoutes");
const coachHealthProgressRoutes = require("./wellnessCoachRoutes/coachHealthProgressRoutes");
const coachMetabolicMetricsRoutes = require("./wellnessCoachRoutes/coachMetabolicMetricsRoutes");
const coachDailyReflectionRoutes = require("./wellnessCoachRoutes/coachDailyReflectionRoutes");
const coachRealPeopleTestimonialRoutes = require("./wellnessCoachRoutes/coachRealPeopleTestimonialRoutes");
const coachCommitmentLetterRoutes = require("./wellnessCoachRoutes/coachCommitmentLetterRoutes");
const coachClientTestimonialRoutes = require("./wellnessCoachRoutes/coachClientTestimonialRoutes");
const coachMonthlyChampionRoutes = require("./wellnessCoachRoutes/coachMonthlyChampionRoutes");
const coachUserCommitmentLetterRoutes = require("./wellnessCoachRoutes/coachUserCommitmentLetterRoutes");
const coachCoachInsightRoutes = require("./wellnessCoachRoutes/coachCoachInsightRoutes");
const coachHealConsultancyTrackRoutes = require("./wellnessCoachRoutes/coachHealConsultancyTrackRoutes");
const coachMealReviewRoutes = require("./wellnessCoachRoutes/coachMealReviewRoutes");
const coachConsultancyRoutes = require("./wellnessCoachRoutes/coachConsultancyRoutes");
const coachEnergyExchangeRoutes = require("./wellnessCoachRoutes/coachEnergyExchangeRoutes");
const coachProgramRoutes = require("./wellnessCoachRoutes/coachProgramRoutes");

const router = express.Router();

router.get("/health", (req, res) => {
  res.json({ ok: true });
});

router.use("/admin/auth", adminAuthRoutes);
router.use("/admin/dashboard", adminDashboardRoutes);
router.use("/coach/auth", coachAuthRoutes);
router.use("/coach/dashboard", coachDashboardRoutes);
router.use("/coach/specializations", coachSpecializationRoutes);
router.use("/coach/heal-users", coachReminderRoutes);
router.use("/coach/heal-users", coachTestRecommendationRoutes);
router.use("/coach/heal-users", coachWellnessPrescriptionRoutes);
router.use("/coach/heal-users", coachDietPlanCatalogRoutes);
router.use("/coach/heal-users", coachPhysicalExerciseRoutes);
router.use("/coach/heal-users", coachMentalWellbeingRoutes);
router.use("/coach/heal-users", coachSupplementRecommendationRoutes);
router.use("/coach/heal-users", coachSupplementDosageRoutes);
router.use("/coach/heal-users", coachMealTrackingRoutes);
router.use("/coach/heal-users", coachLaunchAssessmentRoutes);
router.use("/coach/heal-users", coachPrakrutiAssessmentRoutes);
router.use("/coach/heal-users", coachHealthProgressRoutes);
router.use("/coach/heal-users", coachMetabolicMetricsRoutes);
router.use("/coach/heal-users", coachDailyReflectionRoutes);
router.use("/coach/heal-users", coachUserCommitmentLetterRoutes);
router.use("/coach/heal-users", coachCoachInsightRoutes);
router.use("/coach/heal-users", coachHealConsultancyTrackRoutes);
router.use("/coach/real-people-testimonials", coachRealPeopleTestimonialRoutes);
router.use("/coach/commitment-letters", coachCommitmentLetterRoutes);
router.use("/coach/client-testimonials", coachClientTestimonialRoutes);
router.use("/coach/monthly-champions", coachMonthlyChampionRoutes);
router.use("/coach/meal-tracking", coachMealReviewRoutes);
router.use("/coach/heal-users", coachHealUserRoutes);
router.use("/coach/consultancy", coachConsultancyRoutes);
router.use("/coach/energy-exchange", coachEnergyExchangeRoutes);
router.use("/coach/programs", coachProgramRoutes);
router.use("/admin/app-config", adminAppConfigRoutes);
router.use("/admin/faq", adminFaqRoutes);
router.use("/admin/coupons", adminCouponRoutes);
router.use("/admin/notifications", adminNotificationRoutes);
router.use("/admin/transformations", adminTransformationRoutes);
router.use("/admin/banners", adminBannerRoutes);
router.use("/admin/birthday-notifications", adminBirthdayNotificationRoutes);
router.use("/admin/birthday-posts", adminBirthdayPostRoutes);
router.use("/admin/client-testimonials", adminClientTestimonialsRoutes);
router.use("/admin/leadership-notes", adminLeadershipNoteRoutes);
router.use("/admin/program-testimonials", adminProgramTestimonialRoutes);
router.use("/admin/video-testimonials", adminVideoTestimonialsRoutes);
router.use("/admin/real-people-testimonials", adminRealPeopleTestimonialRoutes);
router.use("/admin/commitment-letters", adminCommitmentLetterRoutes);
router.use("/admin/monthly-champions", adminMonthlyChampionRoutes);
router.use("/admin/cofounder-message", adminCofounderMessageRoutes);
router.use("/admin/contact-inquiries", adminContactInquiryRoutes);
router.use("/admin/consultancy", adminConsultancyRoutes);
router.use("/admin/energy-exchange", adminEnergyExchangeRoutes);
router.use("/admin/programs", adminProgramCatalogRoutes);
router.use("/admin/meal-tracking", adminMealTrackingRoutes);
router.use("/admin/health-concerns", adminHealthConcernRoutes);
router.use("/admin/health-disorders", adminHealthDisorderRoutes);
router.use("/admin/health-tools", adminHealthToolRoutes);
router.use("/admin/health-recipes", adminHealthRecipeRoutes);
router.use("/admin/yoga", adminYogaRoutes);
router.use("/admin/physical-exercises", adminPhysicalExerciseRoutes);
router.use("/admin/supplements", adminSupplementRoutes);
router.use("/admin/medical-condition-questions", adminMedicalConditionQuestionRoutes);
router.use("/admin/launch-questions", adminLaunchQuestionRoutes);
router.use("/admin/launch-focus-areas", adminLaunchFocusAreaRoutes);
router.use("/admin/prakruti-questions", adminPrakrutiQuestionRoutes);
router.use("/admin/prakruti-things-to-avoid", adminPrakrutiThingToAvoidRoutes);
router.use("/admin/prakruti-recommendations", adminPrakrutiRecommendationRoutes);
router.use("/admin/test-catalog", adminTestCatalogRoutes);
router.use("/admin/diet-plan-catalog", adminDietPlanCatalogRoutes);
router.use("/admin/wellness-prescriptions", adminWellnessPrescriptionCatalogRoutes);
router.use("/admin/mental-wellbeing", adminMentalWellbeingRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/heal-users", adminReminderRoutes);
router.use("/admin/heal-users", adminHealDietPlanRoutes);
router.use("/admin/heal-users", adminHealWellnessPrescriptionRoutes);
router.use("/admin/heal-users", adminHealTestRecommendationRoutes);
router.use("/admin/heal-users", adminHealPhysicalExerciseRoutes);
router.use("/admin/heal-users", adminHealMentalWellbeingRoutes);
router.use("/admin/heal-users", adminHealSupplementRecommendationRoutes);
router.use("/admin/heal-users", adminHealSupplementDosageRoutes);
router.use("/admin/heal-users", adminHealMealTrackingRoutes);
router.use("/admin/heal-users", adminHealHealthProgressRoutes);
router.use("/admin/heal-users", adminHealMetabolicMetricsRoutes);
router.use("/admin/heal-users", adminHealDailyReflectionRoutes);
router.use("/admin/heal-users", adminHealConsultancyTrackRoutes);
router.use("/admin/heal-users", adminHealCoachInsightRoutes);
router.use("/admin/heal-users", adminHealUserCommitmentLetterRoutes);
router.use("/admin/heal-users", adminHealLaunchAssessmentRoutes);
router.use("/admin/heal-users", adminHealPrakrutiAssessmentRoutes);
router.use("/admin/wellness-coaches", adminWellnessCoachRoutes);
router.use("/admin/specializations", adminSpecializationRoutes);
router.use("/admin/misc/pages", adminStaticPageRoutes);
router.use("/admin/roles", adminRoleRoutes);
router.use("/admin/permissions", adminPermissionRoutes);
router.use("/user/auth", userAuthRoutes);
router.use("/user/water-tracking", waterTrackingRoutes);
router.use("/user/steps-tracking", stepsTrackingRoutes);
router.use("/user/sleep-tracking", sleepTrackingRoutes);
router.use("/user/heart-rate-tracking", heartRateTrackingRoutes);
router.use("/user/birthday-posts", birthdayPostRoutes);
router.use("/user/notifications", userNotificationRoutes);
router.use("/user/consultancy-payment", consultancyPaymentRoutes);
router.use("/user/subscription-payment", subscriptionPaymentRoutes);
router.use("/user/energy-exchange", energyExchangeRoutes);
router.use("/user/program", programRoutes);
router.use("/user/paid-onboarding", paidOnboardingRoutes);
router.use("/user/reminders", userReminderRoutes);
router.use("/user/real-people-testimonials", userRealPeopleTestimonialRoutes);
router.use("/user/client-testimonials", userClientTestimonialRoutes);
router.use("/user/commitment-letter", commitmentLetterRoutes);
router.use("/user/monthly-champions", monthlyChampionRoutes);
router.use("/user/meal-tracking", userMealTrackingRoutes);
router.use("/user/internal-parameters", internalParameterRoutes);
router.use("/user/diet-plans", dietPlanCatalogRoutes);
router.use("/user/physical-exercises", physicalExerciseRoutes);
router.use("/user/mental-wellbeing", mentalWellbeingRoutes);
router.use("/user/launch-assessment", launchAssessmentRoutes);
router.use("/user/prakruti-assessment", prakrutiAssessmentRoutes);
router.use("/user/health-progress", healthProgressRoutes);
router.use("/user/metabolic-metrics", metabolicMetricsRoutes);
router.use("/user/heal-consultancy-tracks", healConsultancyTrackRoutes);
router.use("/user/daily-reflection", dailyReflectionRoutes);
router.use("/user/coach-insight", coachInsightRoutes);
router.use("/user/supplements", supplementRecommendationRoutes);
router.use("/user/supplements", supplementDosageRoutes);
router.use("/user/wellness-prescriptions", wellnessPrescriptionRoutes);
router.use("/public", publicAppConfigRoutes);
router.use("/public/misc", miscRoutes);

module.exports = router;