const express = require("express");
const adminAuthRoutes = require("./adminRoutes/adminAuthRoutes");
const adminAppConfigRoutes = require("./adminRoutes/adminAppConfigRoutes");
const adminFaqRoutes = require("./adminRoutes/adminFaqRoutes");
const adminCouponRoutes = require("./adminRoutes/adminCouponRoutes");
const adminNotificationRoutes = require("./adminRoutes/adminNotificationRoutes");
const adminStaticPageRoutes = require("./adminRoutes/adminStaticPageRoutes");
const adminTransformationRoutes = require("./adminRoutes/adminTransformationRoutes");
const adminBannerRoutes = require("./adminRoutes/adminBannerRoutes");
const adminHealthConcernRoutes = require("./adminRoutes/adminHealthConcernRoutes");
const adminHealthDisorderRoutes = require("./adminRoutes/adminHealthDisorderRoutes");
const adminHealthToolRoutes = require("./adminRoutes/adminHealthToolRoutes");
const adminHealthRecipeRoutes = require("./adminRoutes/adminHealthRecipeRoutes");
const adminYogaRoutes = require("./adminRoutes/adminYogaRoutes");
const adminUserRoutes = require("./adminRoutes/adminUserRoutes");
const adminWellnessCoachRoutes = require("./adminRoutes/adminWellnessCoachRoutes");
const adminSpecializationRoutes = require("./adminRoutes/adminSpecializationRoutes");
const adminBirthdayNotificationRoutes = require("./adminRoutes/adminBirthdayNotificationRoutes");
const adminBirthdayPostRoutes = require("./adminRoutes/adminBirthdayPostRoutes");
const adminClientTestimonialsRoutes = require("./adminRoutes/adminClientTestimonialsRoutes");
const adminVideoTestimonialsRoutes = require("./adminRoutes/adminVideoTestimonialsRoutes");
const adminCofounderMessageRoutes = require("./adminRoutes/adminCofounderMessageRoutes");
const adminConsultancyRoutes = require("./adminRoutes/adminConsultancyRoutes");
const adminDietPlanRoutes = require("./adminRoutes/adminDietPlanRoutes");
const publicAppConfigRoutes = require("./publicRoutes/publicAppConfigRoutes");
const miscRoutes = require("./userRoutes/miscRoutes");
const userAuthRoutes = require("./userRoutes/authRoutes");
const waterTrackingRoutes = require("./userRoutes/waterTrackingRoutes");
const stepsTrackingRoutes = require("./userRoutes/stepsTrackingRoutes");
const birthdayPostRoutes = require("./userRoutes/birthdayPostRoutes");
const userNotificationRoutes = require("./userRoutes/notificationRoutes");
const consultancyPaymentRoutes = require("./userRoutes/consultancyPaymentRoutes");
const subscriptionPaymentRoutes = require("./userRoutes/subscriptionPaymentRoutes");
const energyExchangeRoutes = require("./userRoutes/energyExchangeRoutes");
const paidOnboardingRoutes = require("./userRoutes/paidOnboardingRoutes");
const userReminderRoutes = require("./userRoutes/reminderRoutes");
const coachAuthRoutes = require("./wellnessCoachRoutes/coachAuthRoutes");
const coachSpecializationRoutes = require("./wellnessCoachRoutes/coachSpecializationRoutes");
const coachAssistantRoutes = require("./wellnessCoachRoutes/coachAssistantRoutes");
const coachHealUserRoutes = require("./wellnessCoachRoutes/coachHealUserRoutes");
const coachReminderRoutes = require("./wellnessCoachRoutes/coachReminderRoutes");
const coachDietPlanRoutes = require("./wellnessCoachRoutes/coachDietPlanRoutes");
const coachConsultancyRoutes = require("./wellnessCoachRoutes/coachConsultancyRoutes");
const coachEnergyExchangeRoutes = require("./wellnessCoachRoutes/coachEnergyExchangeRoutes");
const assistantAuthRoutes = require("./assistantWellnessCoachRoutes/assistantAuthRoutes");
const assistantHealUserRoutes = require("./assistantWellnessCoachRoutes/assistantHealUserRoutes");
const assistantReminderRoutes = require("./assistantWellnessCoachRoutes/assistantReminderRoutes");
const assistantDietPlanRoutes = require("./assistantWellnessCoachRoutes/assistantDietPlanRoutes");
const assistantConsultancyRoutes = require("./assistantWellnessCoachRoutes/assistantConsultancyRoutes");

const router = express.Router();

router.get("/health", (req, res) => {
  res.json({ ok: true });
});

router.use("/admin/auth", adminAuthRoutes);
router.use("/coach/auth", coachAuthRoutes);
router.use("/coach/specializations", coachSpecializationRoutes);
router.use("/coach/assistants", coachAssistantRoutes);
router.use("/coach/heal-users", coachReminderRoutes);
router.use("/coach/heal-users", coachDietPlanRoutes);
router.use("/coach/heal-users", coachHealUserRoutes);
router.use("/coach/consultancy", coachConsultancyRoutes);
router.use("/coach/energy-exchange", coachEnergyExchangeRoutes);
router.use("/assistant/auth", assistantAuthRoutes);
router.use("/assistant/heal-users", assistantReminderRoutes);
router.use("/assistant/heal-users", assistantDietPlanRoutes);
router.use("/assistant/heal-users", assistantHealUserRoutes);
router.use("/assistant/consultancy", assistantConsultancyRoutes);
router.use("/admin/app-config", adminAppConfigRoutes);
router.use("/admin/faq", adminFaqRoutes);
router.use("/admin/coupons", adminCouponRoutes);
router.use("/admin/notifications", adminNotificationRoutes);
router.use("/admin/transformations", adminTransformationRoutes);
router.use("/admin/banners", adminBannerRoutes);
router.use("/admin/birthday-notifications", adminBirthdayNotificationRoutes);
router.use("/admin/birthday-posts", adminBirthdayPostRoutes);
router.use("/admin/client-testimonials", adminClientTestimonialsRoutes);
router.use("/admin/video-testimonials", adminVideoTestimonialsRoutes);
router.use("/admin/cofounder-message", adminCofounderMessageRoutes);
router.use("/admin/consultancy", adminConsultancyRoutes);
router.use("/admin/diet-plans", adminDietPlanRoutes);
router.use("/admin/health-concerns", adminHealthConcernRoutes);
router.use("/admin/health-disorders", adminHealthDisorderRoutes);
router.use("/admin/health-tools", adminHealthToolRoutes);
router.use("/admin/health-recipes", adminHealthRecipeRoutes);
router.use("/admin/yoga", adminYogaRoutes);
router.use("/admin/users", adminUserRoutes);
router.use("/admin/wellness-coaches", adminWellnessCoachRoutes);
router.use("/admin/specializations", adminSpecializationRoutes);
router.use("/admin/misc/pages", adminStaticPageRoutes);
router.use("/user/auth", userAuthRoutes);
router.use("/user/water-tracking", waterTrackingRoutes);
router.use("/user/steps-tracking", stepsTrackingRoutes);
router.use("/user/birthday-posts", birthdayPostRoutes);
router.use("/user/notifications", userNotificationRoutes);
router.use("/user/consultancy-payment", consultancyPaymentRoutes);
router.use("/user/subscription-payment", subscriptionPaymentRoutes);
router.use("/user/energy-exchange", energyExchangeRoutes);
router.use("/user/paid-onboarding", paidOnboardingRoutes);
router.use("/user/reminders", userReminderRoutes);
router.use("/public", publicAppConfigRoutes);
router.use("/public/misc", miscRoutes);

module.exports = router;