const { coachHandlers } = require("../helpers/launchAssessmentControllerHelpers");

exports.listCoachUserLaunchFocusAreasController = coachHandlers.listFocusAreasController;
exports.getCoachUserLaunchConfigController = coachHandlers.getConfigController;
exports.listCoachUserLaunchQuestionsController = coachHandlers.listQuestionsController;
exports.listCoachUserLaunchAssessmentsController = coachHandlers.listAssessmentsController;
exports.getCoachUserLaunchAssessmentByDateController = coachHandlers.getAssessmentByDateController;
exports.createCoachUserLaunchAssessmentController = coachHandlers.createAssessmentController;
exports.updateCoachUserLaunchAssessmentController = coachHandlers.updateAssessmentController;
exports.deleteCoachUserLaunchAssessmentController = coachHandlers.deleteAssessmentController;
exports.exportCoachUserLaunchQuestionsController = coachHandlers.exportQuestionsController;
