const { coachHandlers } = require("../helpers/prakrutiAssessmentControllerHelpers");

exports.listCoachUserPrakrutiThingsToAvoidController = coachHandlers.listThingsToAvoidController;
exports.listCoachUserPrakrutiQuestionsController = coachHandlers.listQuestionsController;
exports.listCoachUserPrakrutiRecommendationsController = coachHandlers.listRecommendationsController;
exports.getCoachUserPrakrutiAssessmentController = coachHandlers.getAssessmentController;
exports.saveCoachUserPrakrutiAssessmentController = coachHandlers.saveAssessmentController;
exports.exportCoachUserPrakrutiQuestionsController = coachHandlers.exportQuestionsController;
